### ISSUE TITLE
Webots crashes on startup

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#127]
**Describe the Bug**

On some hardware, Webots R2019a crashes on startup.

**Screenshots**

![capture](https://user-images.githubusercontent.com/866788/51541404-05d0bf80-1e59-11e9-9bfd-7c6b0f6e0e92.JPG)

_(from ticket #324)_ 

**System**
 
It seems to affect mainly Windows users, without guarantee for now.
The bug have been reproduced with the following GPU:
  - AMD Radeon(TM) R7 M440 (0x6900)
  - AMD Radeon 6600M and 6700M Series
  - NVIDIA Corporation - GeForce 840M/PCIe/SSE2 - 3.3.0 NVIDIA 376.54
  - NVIDIA Corporation - GeForce 540M - 3.3.0

**Comment by fabienrohrer** [comment]
A user fails the procedure at step 2. He can run "empty.wbt" but not "geometric_primitives.wbt" whatever the preferences of step 3.

**Comment by DavidMansolino** [comment]
It seems the problem comes from HDR background. Non HDR background + PBR + Bloom + GTAO is working fine.

**Comment by DavidMansolino** [comment]
The problem seems to be the backing of the specular irradiance, disabling it fixes the crash.

**Comment by DavidMansolino** [comment]
Reducing the resolution of the specular irradiance cubemap texture from 512 to 128 (and also the number of mimaps from 10 to 8) fixes the problem, I can now run all the worlds of the guided tour.

Since this resolution is not yet linked to the texture quality preference I propose to link it to it, so that it will work in low-quality texture mode.
Then we will need a way to detect these problematic GPUs and switch automatically to the low texture quality mode (the GPU I am currently testing have 1Gb of dedicated memory which is not so low).

**Comment by DavidMansolino** [comment]
I have made a few comparisons to check the impact on the rendering (please make sure to compare them at full resolution and not only the small preview):

| resolution | metalness 1 | metalness 0 |
| ------------- | ---------------- | --------------- |
|     512       | ![512](https://user-images.githubusercontent.com/2461619/51622148-4f430c80-1f36-11e9-84f3-cca97ce81b71.png) | ![512_2](https://user-images.githubusercontent.com/2461619/51622154-51a56680-1f36-11e9-9f80-7c2c302294cb.png) |
|     256 | ![256](https://user-images.githubusercontent.com/2461619/51622409-d5f7e980-1f36-11e9-9626-2cf240197a0c.png) | ![256_2](https://user-images.githubusercontent.com/2461619/51622411-d7c1ad00-1f36-11e9-8df0-2a6a8bd051a2.png) |
|     128  | ![128](https://user-images.githubusercontent.com/2461619/51622174-59fda180-1f36-11e9-9273-9beb7e12d77d.png) | ![128_2](https://user-images.githubusercontent.com/2461619/51622180-5d912880-1f36-11e9-98d6-400a94929737.png) |
|      32  |  ![32](https://user-images.githubusercontent.com/2461619/51622199-68e45400-1f36-11e9-9303-890bf5e98515.png) |  ![32_2](https://user-images.githubusercontent.com/2461619/51622212-6bdf4480-1f36-11e9-9843-f0f8f9316ae3.png) |
|       8 | ![8](https://user-images.githubusercontent.com/2461619/51622231-739ee900-1f36-11e9-8f83-820af252bfea.png) |  ![8_2](https://user-images.githubusercontent.com/2461619/51622237-77327000-1f36-11e9-82f0-2cf59cb423cc.png) |

As the difference is almost invisible between 512 and 256, here is what I propose:
  - Put 256 instead of 512 by default.
  - Put 128 in medium texture resolution.
  - Put 64 in low texture resolution.
  - Switch automatically to 'medium' texture resolution for GPU with less than 2gb of memory.
  - Switch automatically to 'low' texture resolution for GPU with less than 1gb of memory.

**Comment by omichel** [comment]
That seems to be a very good proposal.
