### ISSUE TITLE
Buggy rendering order with ElevationGrid

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#330]
**Describe the Bug**
Some parts of the ElevationGrid are wrongly rendered above others.

**Steps to Reproduce**
1. Go to "tests/api/worlds/pen_elevation_grid.wbt"
2. Change the BOARD shape texture to make it more visible.

**Screenshots**

![elevation_grid_bug](https://user-images.githubusercontent.com/5910449/55392305-4fb1e200-553b-11e9-9bbd-92d1032dfdb5.png)

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: NVIDIA  GeForce GT 740/PCIe/SSE2

**Comment by fabienrohrer** [comment]
This is because `color_checker_chart.png` has an alpha channel. The shape is rendered without depth check, so the polygon order maters.

@stefaniapedrazzi Is it a sufficient answer? Could we close this issue?

**Comment by stefaniapedrazzi** [comment]
Thank you for the explanation but this is in any case a bug.
In THREEjs this object is rendered correctly so this is a specific issue of WREN.

**Comment by omichel** [comment]
If that's a bug, we shouldn't close the issue. Can't we simply simply remove the alpha channel from this texture image which doesn't seem to need it?

**Comment by omichel** [comment]
PNG images should be used only when we need an alpha channel, as they are usually bigger than their equivalent JPEG images. So, any PNG texture that doesn't need transparency or alpha blending should be converted to a JPEG texture.

**Comment by stefaniapedrazzi** [comment]
> If that's a bug, we shouldn't close the issue. Can't we simply simply remove the alpha channel from this texture image which doesn't seem to need it?

This was just a test world created to check the ElevationGrid texture mapping and I picked the first image I found without checking if it had alpha channel or not.

**Comment by fabienrohrer** [comment]
To generalize the discussion, I think this is not a bug but an implementation choice. It's a matter of how we sort the polygons in case of a transparent material. Currently we do nothing to save resources. It's not a bad choice.

About JPEG vs PNG, I completely agree to remove alpha when unneeded, but the present image is a typical example where the PNG format (3Ko) has a smaller size than the JPEG format (30Ko) because of its big homogenous areas. JPEG should be used for real pictures rather.

**Comment by stefaniapedrazzi** [comment]
The alpha channel in `color_checker_chart.png` has been removed.
