### ISSUE TITLE
How to change line width of IndexedLineSet 

### ISSUE THREAD

**Issue by lesun90** [omichel/webots#385]
I want to change the linewidth of the indexedLineSet, is there any possible way to do this?

Thank you.

**Comment by fabienrohrer** [comment]
Unfortunately, the line width is not an open parameter.

This should be possible by calling `glLineWidth()` at the right place in "wren" (the rendering engine of Webots), and build Webots by yourself. But I remember we had issues with this: If I remember well think `glLineWidth` is not a part of `glad`.

Alternatively, couldn't you use the Extrusion PROTO to define a thick line shape? https://cyberbotics.com/doc/guide/samples-geometries#extrusion-wbt

**Comment by lesun90** [comment]
Thank you for your reply and suggestion. I think using a polygon shape should easier in this case.
Anyway, it will be awesome if you guys could bring back feature of drawing using OpenGL, or improve the display device so it has better drawing capability (eg: draw in 3D, draw use coordinate - not pixel)

**Comment by fabienrohrer** [comment]
You're right. We decided to drop this feature because giving a clean OpenGL state to the user is not very obvious in our new rendering workflow and users were often breaking the rendering :-) But giving more drawing abilities, maybe from new supervisor functions, is definitively a good idea.

You're also probably aware of this example: https://cyberbotics.com/doc/guide/samples-howto#supervisor_draw_trail-wbt

**Comment by lesun90** [comment]
I will absolutely look forward to that feature, right now, I just using supervisor to create shape such as line, polygon, etc...

Thank you.
