### ISSUE TITLE
Java Installation Instruction not Working on Ubuntu 16.04

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#650]
**Describe the Bug**
These installation instructions are not working on Ubuntu 16.04 anymore: https://www.cyberbotics.com/doc/guide/using-java#linux

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
```

**Comment by stefaniapedrazzi** [comment]
The "issue" should affect all the platforms.

The webupd8team's PPA has been discontinued due to changes in the Oracle Java License Agreement that now require to be logged in to download the JDK package.

https://launchpad.net/~webupd8team/+archive/ubuntu/java

Oracle Java SE Licensing FAQ:
https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html

**Comment by stefaniapedrazzi** [comment]
Oracle provides open source builds for Windows and macOs but only of JDK >= 12 on https://jdk.java.net
