### ISSUE TITLE
Asynchronous setPosition movement

### ISSUE THREAD

**Issue by NamelessSuperCoder** [omichel/webots#711]
So we have a robot that has 6 DOF and we want to make the robot got to specific positions
 smoothly; however, when using the setPosition method it only makes the robot move one joint at a time.

To see this happen:

1. Download this *.zip:
[MinimalisticExample.zip](https://github.com/omichel/webots/files/3383643/MinimalisticExample.zip)
2. Open the MinimalisticExample.wbt
3. Run the simulation

As you can see the robot joints are moving sequentially: one after the other. The next one only moves once the others have reached their targets.

![MinimalisticExample](https://user-images.githubusercontent.com/19751068/61086637-59cc6200-a401-11e9-8062-cd6ff0b74df1.gif)

What we would like to see happen is that all the setPosition move at the same time instead. We are aware of setVelocity; however, it would make out life a lot easier if we can just the positions. Also doing setPosition in very small increments like in the ABB example is not what we would like to have to do as that would require us to restructure our code completely.

There are our computer/software specs:
- Windows 10 (latest update)
- Webots R2019b

Many thanks!

**Comment by DavidMansolino** [comment]
The motions of the motor are actually done in parallel, but one of them is going way faster than the other.
This is probably because the second motor doesn't have enought torque to move it faster.
I have set the `maxTorque` of both motors to 100 and the `maxVelocity` to 1 (to better see the motion), and here is the result (you can see both joints are moving in parallel).

![ezgif-4-fd854fe4c415](https://user-images.githubusercontent.com/2461619/61120402-3b1ba900-a49d-11e9-9cff-1160791e17e8.gif)

You can also see from the position sensors that both are moving at the same time:
![Capture du 2019-07-12 12-07-13](https://user-images.githubusercontent.com/2461619/61120602-a2395d80-a49d-11e9-8c68-528fbd933656.png)

Let me know if anything is unclear.
Please find the modified simulation here: 
[MinimalisticExample.zip](https://github.com/omichel/webots/files/3385991/MinimalisticExample.zip)

**Comment by NamelessSuperCoder** [comment]
Thank you very much it seems that this is working! It might be a good idea to put this in the documentation somewhere so that other people know that setPosition might not work if you do not have enough available torque or force.
